export const CLIENTES = [
  {
    nombre: 'Juan',
    apellido: 'Pérez',
    email: 'juan.perez@email.com',
    telefono: '987654321',
    direccion: 'Av. Siempre Viva 123',
    ciudad: 'Lima',
    pais: 'Perú',
  },
  {
    nombre: 'María',
    apellido: 'García',
    email: 'maria.garcia@email.com',
    telefono: '912345678',
    direccion: 'Calle Falsa 456',
    ciudad: 'Arequipa',
    pais: 'Perú',
  },
  {
    nombre: 'Carlos',
    apellido: 'Ramírez',
    email: 'carlos.ramirez@email.com',
    telefono: '998877665',
    direccion: 'Jr. Los Olivos 789',
    ciudad: 'Cusco',
    pais: 'Perú',
  },
  {
    nombre: 'Ana',
    apellido: 'Torres',
    email: 'ana.torres@email.com',
    telefono: '934567890',
    direccion: 'Av. El Sol 321',
    ciudad: 'Trujillo',
    pais: 'Perú',
  },
  {
    nombre: 'Luis',
    apellido: 'Fernández',
    email: 'luis.fernandez@email.com',
    telefono: '976543210',
    direccion: 'Calle Luna 654',
    ciudad: 'Piura',
    pais: 'Perú',
  },
  {
    nombre: 'Rosa',
    apellido: 'Mendoza',
    email: 'rosa.mendoza@email.com',
    telefono: '945123789',
    direccion: 'Av. Los Incas 890',
    ciudad: 'Huancayo',
    pais: 'Perú',
  },
  {
    nombre: 'Miguel',
    apellido: 'Vargas',
    email: 'miguel.vargas@email.com',
    telefono: '967834521',
    direccion: 'Calle San Martín 234',
    ciudad: 'Chiclayo',
    pais: 'Perú',
  },
  {
    nombre: 'Elena',
    apellido: 'Castillo',
    email: 'elena.castillo@email.com',
    telefono: '923456789',
    direccion: 'Jr. Libertad 567',
    ciudad: 'Iquitos',
    pais: 'Perú',
  },
  {
    nombre: 'Roberto',
    apellido: 'Jiménez',
    email: 'roberto.jimenez@email.com',
    telefono: '981234567',
    direccion: 'Av. Universitaria 1123',
    ciudad: 'Tacna',
    pais: 'Perú',
  },
  {
    nombre: 'Patricia',
    apellido: 'Morales',
    email: 'patricia.morales@email.com',
    telefono: '956789123',
    direccion: 'Calle Comercio 445',
    ciudad: 'Ayacucho',
    pais: 'Perú',
  },
  {
    nombre: 'Diego',
    apellido: 'Herrera',
    email: 'diego.herrera@email.com',
    telefono: '932567890',
    direccion: 'Av. Grau 678',
    ciudad: 'Cajamarca',
    pais: 'Perú',
  },
  {
    nombre: 'Carmen',
    apellido: 'Quispe',
    email: 'carmen.quispe@email.com',
    telefono: '978901234',
    direccion: 'Jr. Huáscar 789',
    ciudad: 'Puno',
    pais: 'Perú',
  },
  {
    nombre: 'Fernando',
    apellido: 'Silva',
    email: 'fernando.silva@email.com',
    telefono: '943210987',
    direccion: 'Calle Bolívar 321',
    ciudad: 'Tumbes',
    pais: 'Perú',
  },
  {
    nombre: 'Lucía',
    apellido: 'Ramos',
    email: 'lucia.ramos@email.com',
    telefono: '965432109',
    direccion: 'Av. Independencia 654',
    ciudad: 'Huaraz',
    pais: 'Perú',
  },
  {
    nombre: 'Jorge',
    apellido: 'Vega',
    email: 'jorge.vega@email.com',
    telefono: '987012345',
    direccion: 'Jr. Junín 987',
    ciudad: 'Chimbote',
    pais: 'Perú',
  },
];

export const PRODUCTOS = [
  {
    nombre: 'Laptop Lenovo ThinkPad',
    descripcion:
      'Laptop empresarial de 14 pulgadas, Intel Core i5, 8GB RAM, 256GB SSD',
    precio: 3200.0,
    stock: 15,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Mouse Inalámbrico Logitech',
    descripcion: 'Mouse inalámbrico ergonómico, 1600 DPI, USB',
    precio: 80.0,
    stock: 50,
    categoria: 'Accesorios',
  },
  {
    nombre: 'Monitor Samsung 24"',
    descripcion: 'Monitor LED Full HD, 24 pulgadas, HDMI/VGA',
    precio: 650.0,
    stock: 20,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Teclado Mecánico Redragon',
    descripcion: 'Teclado mecánico retroiluminado, switches blue',
    precio: 180.0,
    stock: 30,
    categoria: 'Accesorios',
  },
  {
    nombre: 'Silla Ergonómica de Oficina',
    descripcion: 'Silla con soporte lumbar, ajustable, color negro',
    precio: 450.0,
    stock: 10,
    categoria: 'Muebles',
  },
  {
    nombre: 'Smartphone Samsung Galaxy A54',
    descripcion: 'Smartphone Android, pantalla 6.4", 128GB, cámara 50MP',
    precio: 1200.0,
    stock: 25,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Auriculares Sony WH-CH720N',
    descripcion: 'Auriculares inalámbricos con cancelación de ruido',
    precio: 320.0,
    stock: 35,
    categoria: 'Audio',
  },
  {
    nombre: 'Escritorio de Madera Oak',
    descripcion: 'Escritorio ejecutivo de madera maciza, 150x80cm',
    precio: 890.0,
    stock: 8,
    categoria: 'Muebles',
  },
  {
    nombre: 'Impresora HP LaserJet Pro',
    descripcion: 'Impresora láser monocromática, WiFi, dúplex automático',
    precio: 580.0,
    stock: 12,
    categoria: 'Oficina',
  },
  {
    nombre: 'Webcam Logitech C920',
    descripcion: 'Cámara web Full HD 1080p, micrófono integrado',
    precio: 150.0,
    stock: 40,
    categoria: 'Accesorios',
  },
  {
    nombre: 'Tablet iPad Air 5ta Gen',
    descripcion: 'Tablet Apple, pantalla 10.9", 64GB, chip M1',
    precio: 2100.0,
    stock: 18,
    categoria: 'Tecnología',
  },
  {
    nombre: 'Router TP-Link Archer AX73',
    descripcion: 'Router WiFi 6, velocidad hasta 5.4Gbps, 6 antenas',
    precio: 280.0,
    stock: 22,
    categoria: 'Redes',
  },
  {
    nombre: 'Disco Duro Externo Seagate 2TB',
    descripcion: 'Disco duro portátil USB 3.0, 2TB de capacidad',
    precio: 220.0,
    stock: 28,
    categoria: 'Almacenamiento',
  },
  {
    nombre: 'Lámpara LED de Escritorio',
    descripcion: 'Lámpara articulada con control de intensidad y temperatura',
    precio: 95.0,
    stock: 45,
    categoria: 'Iluminación',
  },
  {
    nombre: 'Cargador Inalámbrico Anker',
    descripcion: 'Base de carga inalámbrica 15W, compatible con Qi',
    precio: 65.0,
    stock: 60,
    categoria: 'Accesorios',
  },
];
